'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GoogleMap

    '''<summary>
    '''dvPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''dvForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblShapeFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShapeFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FarmName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FarmName As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''FarmXY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FarmXY As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''FieldsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FieldsName As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''FieldsArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FieldsArea As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''FieldsXY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FieldsXY As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''StateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateName As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''StateAbbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateAbbr As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''CountyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountyName As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''savedata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents savedata As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TextAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''Textlatlng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Textlatlng As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblFarmShp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFarmShp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fileUploadFarmShapefile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileUploadFarmShapefile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblFieldShp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFieldShp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fileUploadFieldShapefile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileUploadFieldShapefile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''bntUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_lblNote1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lblNote1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNote2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNote2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNavigation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''trNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNavigation As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblNoteNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoteNavigation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddress As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblLatLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLatLon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgLatlng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLatlng As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblZoomState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZoomState As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lblZoomCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZoomCounty As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''stateselect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stateselect As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''countyAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents countyAll As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''lblTools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTools As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''trTools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTools As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblToolsNote1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToolsNote1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblToolsNote2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToolsNote2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblToolsNote4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToolsNote4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblToolsNote3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToolsNote3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblEditingOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditingOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblField As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDelete As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''savebutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents savebutton As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

    '''<summary>
    '''submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblNote5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNote5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFieldName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFieldName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFieldName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFieldName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCopyFarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyFarm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCopyFarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCopyFarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''map control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents map As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MsgBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBox1 As Global.BunnyBear.msgBox

    '''<summary>
    '''dvWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvWait As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
