'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Management

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tblGeneralInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblGeneralInfo As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''trGemeralInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGemeralInfo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFields As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFields As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdnField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnField As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lblScenarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenarios As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlScenarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScenarios As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdnScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnScenario As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnDeleteScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteScenario As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtScenarioName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScenarioName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddNewScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewScenario As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRenameScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRenameScenario As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtScenarioRenamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScenarioRenamed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''aTvMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aTvMain As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''tvMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvMain As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''tdCurrentScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdCurrentScenario As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''fsetCroppingSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetCroppingSystem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCroppingSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCroppingSystem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSelectCroppingSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectCroppingSystem As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlCroppingSystems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCroppingSystems As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlCroppingSystemsAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCroppingSystemsAll As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''lblTillage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTillage As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlTillageAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTillageAll As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fsetLoadCropping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetLoadCropping As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLoadCropping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoadCropping As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnUploader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploader As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''flUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents flUpload As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''btnOpenCropping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOpenCropping As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fsetCopyCropping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetCopyCropping As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCopyCropping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCopyCropping As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFromField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFromField As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlFromField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFromField As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''lblFromScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFromScenario As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlFromScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFromScenario As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlAllScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAllScenario As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''btnCopyCropping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyCropping As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''fsetOperations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetOperations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnAddOperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddOperation As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDeleteOperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOperation As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnMixePasture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMixePasture As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''ddlCrops control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCrops As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlOpers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOpers As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlYears As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMonths As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDays As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTypes As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ctlSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlSave As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''gvOperations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOperations As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''aOpReadHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aOpReadHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetAI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAIIrrigationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIIrrigationType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIWaterStress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIWaterStress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIEfficiancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIEfficiancy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIFrequency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIMaxSingleAppl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIMaxSingleAppl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIResArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIResArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAISafetyFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAISafetyFactor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAIIrrigationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAIIrrigationType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAIWaterStress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAIWaterStress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAIIrrigationEfficiancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAIIrrigationEfficiancy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAIFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAIFrequency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAIMaxSingleAppl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAIMaxSingleAppl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAIResArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAIResArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAISafetyFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAISafetyFactor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAIClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAIClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aAIHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aAIHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetAF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAFIrrigationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAFIrrigationType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAFWaterStress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAFWaterStress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAFEfficiancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAFEfficiancy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAFFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAFFrequency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAFMaxSingleAppl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAFMaxSingleAppl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAFNConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAFNConc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAFSafetyFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAFSafetyFactor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAFIrrigationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAFIrrigationType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAFWaterStress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAFWaterStress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAFIrrigationEfficiancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAFIrrigationEfficiancy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAFFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAFFrequency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAFMaxSingleAppl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAFMaxSingleAppl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAFNConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAFNConc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAFSafetyFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAFSafetyFactor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAFClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAFClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aAFHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aAFHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetTD As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTD As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTDDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTDDepth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTDDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDDepth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnTDClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTDClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aTDHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aTDHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetPPND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetPPND As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPND As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPNDWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPNDWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPNDWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPNDWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPNDSides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPNDSides As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPNDSides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPNDSides As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPPNDClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPPNDClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aPPNDHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aPPNDHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetPPDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetPPDS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPDS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPDSWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPDSWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPDSWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPDSWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPDSSides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPDSSides As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPDSSides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPDSSides As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPPDSClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPPDSClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aPPDSHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aPPDSHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetPPDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetPPDE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPDE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPDEResArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPDEResArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPDEResArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPDEResArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPDEWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPDEWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPDEWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPDEWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPDESides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPDESides As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPDESides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPDESides As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPPDEClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPPDEClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aPPDEHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aPPDEHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetPPTW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetPPTW As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPTW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPTW As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPPTWResArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPTWResArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPTWResArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPTWResArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPTWWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPTWWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPTWWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPTWWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPTWSides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPTWSides As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPTWSides control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPTWSides As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPPTWClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPPTWClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aPPTWHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aPPTWHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetWL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetWL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWLArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWLArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWLArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWLArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnWLClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWLClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aWLHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aWLHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetPND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetPND As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPND As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPNDFraction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPNDFraction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPNDFraction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPNDFraction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPNDClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPNDClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aPNDHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aPNDHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetSF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetSF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSFAimals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFAimals As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFDays As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFHours As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFManure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFManure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSFAnimals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFAnimals As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSFDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFDays As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSFHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFHours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSFType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSFType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSFManure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFManure As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSFNutrients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFNutrients As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFNO3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFNO3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFPO4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFPO4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFOrgN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFOrgN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFOrgP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFOrgP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSFMH3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSFMH3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSFNO3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFNO3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSFPO4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFPO4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSFOrgN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFOrgN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSFOrgP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFOrgP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSFNH3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSFNH3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSFClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSFClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aSFHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aSFHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetSBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetSBS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSBS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkSBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSBS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSBSClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSBSClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aSBSHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aSBSHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetRF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetRF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRFArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRFArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRFWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRFWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRFGrass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRFGrass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRFRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRFRatio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRFArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRFArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRFWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRFWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRFGrass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRFGrass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRFRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRFRatio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRFClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRFClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aRFHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aRFHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetFS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetFS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFSType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFSType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFSArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFSArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFSWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFSWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFSRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFSRatio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFSType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFSType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFSArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFSArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFSWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFSWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFSRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFSRatio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnFSClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFSClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aFSHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aFSHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetWW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetWW As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWW As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWWType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWWType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWWWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWWWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlWWType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWWType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWWWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWWWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnWWClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWWClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aWWHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aWWHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetCB As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCB As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCBType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCBType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCBBufferWith control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCBBufferWith As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCBCropWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCBCropWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCBType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCBType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCBBufferWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBBufferWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCBCropWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBCropWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCBClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCBClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aCBHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aCBHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetLL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetLL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReduction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLLReduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLLReduction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnLLClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLLClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aLLHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aLLHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetTS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnTSClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTSClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aTSHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aTSHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetMC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMC As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblMCType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMCType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMCType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMCType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblNutrientsAdj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNutrientsAdj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNO3NAdj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNO3NAdj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmcNO3N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmcNO3N As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblmcOrgN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmcOrgN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmcOrgN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmcOrgN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblmcPO4P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmcPO4P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmcPO4P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmcPO4P As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblmcOrgP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmcOrgP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmcOrgP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmcOrgP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblmcOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmcOM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmcOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmcOM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnMCClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMCClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aMCHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aMCHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''tblNoMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNoMC As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblNoMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoMC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''a2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetLM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetLM As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLM As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkLM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnLMClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLMClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aLMHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aLMHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetCC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCCMinTmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCMinTmp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCCMinTmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCMinTmp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCCMaxTmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCMaxTmp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCCMaxTmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCMaxTmp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCCPcp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCPcp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCCPcp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCPcp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCCClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCCClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''a1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetAoC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetAoC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAoC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAoC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkAoC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAoC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnAoCClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAoCClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aAoCHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aAoCHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetGC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnGCClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGCClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aGCHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aGCHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetSA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSAClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSAClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aSAHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aSAHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fsetSdg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetSdg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSdg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSdg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSdgCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSdgCrop As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSdgArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSdgArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSdgWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSdgWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSdgSlopeRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSdgSlopeRatio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSdgCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSdgCrop As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSdgArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSdgArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSdgWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSdgWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSdgSlopeRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSdgSlopeRatio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSdgClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSdgClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aSdgHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aSdgHide As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblFerts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFerts As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSaveMixedCrops control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveMixedCrops As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvCrops control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCrops As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdnOperationNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnOperationNumber As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
