'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Modifications

    '''<summary>
    '''lblFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFile As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFields As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFields As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSoils control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoils As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSoils control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSoils As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblScenarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenarios As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlScenarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScenarios As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDownloadAPEX1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownloadAPEX1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnSaveContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveContinue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''fsetControlfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetControlfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControl As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnDefaultControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDefaultControl As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''gvControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvControls As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''fsetParamfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetParamfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblParmFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParmFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnDefaultParms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDefaultParms As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''gvParms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvParms As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''fsetSubareafile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetSubareafile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSubarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubarea As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvSubarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubarea As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''fsetSoilfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetSoilfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSoil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoil As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvSoils control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSoils As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''fsetLayerfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetLayerfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLayerFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLayerFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvLayer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLayer As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''fsetOperationfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetOperationfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvOperation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOperation As Global.System.Web.UI.WebControls.GridView
End Class
