'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Simulation

    '''<summary>
    '''btnSaveContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveContinue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlType As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''lblScenarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenarios As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divScenario As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblField As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlField As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScenario As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlScenario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScenario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddSimulations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSimulations As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''divSubproject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubproject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSubproject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubproject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlSubproject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubproject As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddSubproject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSubproject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnAddAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAll As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnRemoveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveAll As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''fsetSimulation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetSimulation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSimuation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSimuation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSimulation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSimulation As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''fsetListSimulations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetListSimulations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRunSimulation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunSimulation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnRunEnvironment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunEnvironment As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnRunEconomic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunEconomic As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''gvSimulations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSimulations As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Legend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Legend1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
