'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Weather

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblWeatherTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeatherTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rbtnStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnStation As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lblStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rbtnOwn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnOwn As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lblOwn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOwn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rbtnCoordinates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnCoordinates As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''lblCoordinates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoordinates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tdWeather control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdWeather As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''fsetStations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetStations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlStations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStations As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''fsetUploadWeatherFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetUploadWeatherFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUploadWeatherFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUploadWeatherFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''flUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents flUpload As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''fsetCoordinates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsetCoordinates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCoordinates1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoordinates1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLong As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveCoordinates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCoordinates As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblYearsOfInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYearsOfInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWeatherYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeatherYears As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSimulationNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSimulationNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeriodToSimulate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodToSimulate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPeriodFromSimulate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodFromSimulate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPeriodToSimulate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodToSimulate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSimulationPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSimulationPeriod As Global.System.Web.UI.WebControls.Label
End Class
