'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace HUService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://tempuri.org/", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="HUService.Service1Soap")>  _
    Public Interface Service1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getHU", ReplyAction:="*")>  _
        Function getHU(ByVal crop As Short, ByVal nlat As Single, ByVal nlon As Single) As Single
        
        'CODEGEN: Generating message contract since element name GetWeatherFileResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetWeatherFile", ReplyAction:="*")>  _
        Function GetWeatherFile(ByVal request As HUService.GetWeatherFileRequest) As HUService.GetWeatherFileResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetWeatherFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetWeatherFile", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As HUService.GetWeatherFileRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As HUService.GetWeatherFileRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetWeatherFileRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public nlat As Single
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nlon As Single
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nlat As Single, ByVal nlon As Single)
            MyBase.New
            Me.nlat = nlat
            Me.nlon = nlon
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetWeatherFileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetWeatherFileResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As HUService.GetWeatherFileResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As HUService.GetWeatherFileResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetWeatherFileResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetWeatherFileResult As HUService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetWeatherFileResult As HUService.ArrayOfString)
            MyBase.New
            Me.GetWeatherFileResult = GetWeatherFileResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Service1SoapChannel
        Inherits HUService.Service1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1SoapClient
        Inherits System.ServiceModel.ClientBase(Of HUService.Service1Soap)
        Implements HUService.Service1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getHU(ByVal crop As Short, ByVal nlat As Single, ByVal nlon As Single) As Single Implements HUService.Service1Soap.getHU
            Return MyBase.Channel.getHU(crop, nlat, nlon)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function HUService_Service1Soap_GetWeatherFile(ByVal request As HUService.GetWeatherFileRequest) As HUService.GetWeatherFileResponse Implements HUService.Service1Soap.GetWeatherFile
            Return MyBase.Channel.GetWeatherFile(request)
        End Function
        
        Public Function GetWeatherFile(ByVal nlat As Single, ByVal nlon As Single) As HUService.ArrayOfString
            Dim inValue As HUService.GetWeatherFileRequest = New HUService.GetWeatherFileRequest()
            inValue.Body = New HUService.GetWeatherFileRequestBody()
            inValue.Body.nlat = nlat
            inValue.Body.nlon = nlon
            Dim retVal As HUService.GetWeatherFileResponse = CType(Me,HUService.Service1Soap).GetWeatherFile(inValue)
            Return retVal.Body.GetWeatherFileResult
        End Function
    End Class
End Namespace
