'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace GetSoilsInfo
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="GetSoilsInfo.SoilsSoap")>  _
    Public Interface SoilsSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSoilsInfo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetSoilsInfo(ByVal InputLatLong As String, ByVal stateName As String, ByVal ssaCode As String, ByVal urban As String) As System.Data.DataTable
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SoilsSoapChannel
        Inherits GetSoilsInfo.SoilsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SoilsSoapClient
        Inherits System.ServiceModel.ClientBase(Of GetSoilsInfo.SoilsSoap)
        Implements GetSoilsInfo.SoilsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetSoilsInfo(ByVal InputLatLong As String, ByVal stateName As String, ByVal ssaCode As String, ByVal urban As String) As System.Data.DataTable Implements GetSoilsInfo.SoilsSoap.GetSoilsInfo
            Return MyBase.Channel.GetSoilsInfo(InputLatLong, stateName, ssaCode, urban)
        End Function
    End Class
End Namespace
